# Google BigQuery Params
servicekey_path: '' # Path to Google BigQuery Credentials
project_name: 'dmrc-data'
dataset_name: 'WordFlow_AnalyticsEngine'
tablename: 'lv_test_delete'

id_column: 'link'
text_column: 'content'

from_database: False
from_csv: True

language: 'en'
named_entity_recognition: False
part_of_speech: True
sentiment: False

stanza: True
spacy: False
nltk: False
