# Google BigQuery Params
servicekey_path: '' # Path to Google BigQuery Credentials
project_name: 'dmrc-data'
dataset_name: 'WordFlow_AnalyticsEngine'
tablename: 'test_random_text_8'

id_column: 'identificator'
text_column: 'message'

from_database: True
from_csv: False

language: 'en'

named_entity_recognition: False
part_of_speech: False
dependency_parsing: True
sentiment: False

stanza: False
spacy: True
nltk: False
