
id_column: 'article_id'
text_column: 'content'

language: 'en'

named_entity_recognition: True
part_of_speech: False
dependency_parsing: False
sentiment: False
morphology: False

stanza: True
spacy: False

